name: Call build-test-deploy reusable workflow

# cancel any other jobs in progress
#concurrency: 
#  group: build-test-deploy
#  cancel-in-progress: true

on:
  push:
    branches:
      - stage
  release:
    types:
      - published

  
# Required Secrets:
# ECS_SERVICE_INSTANCE_NAME_STAGE
# ECS_SERVICE_INSTANCE_NAME_PROD
# SLACK_CHANNEL
# REDIS_RELOAD
# SEC_CHECK_DISABLED


jobs:            
  call-workflow:
    if: github.repository != 'avatarnewyork/.github'
    uses: avatarnewyork/.github/.github/workflows/build_test_deploy.yml@master
    secrets: inherit
    with:
      php_version: 8.0.20
      build_version: latest
