name: Build, Test, Deploy 

# cancel any other jobs in progress
#concurrency: 
#  group: build-test-deploy
#  cancel-in-progress: true

on:
  push:
    branches:
      - stage
  release:
    types:
      - published

  
# Required Secrets:
# ECS_SERVICE_INSTANCE_NAME_STAGE
# ECS_SERVICE_INSTANCE_NAME_PROD
# SLACK_CHANNEL
# REDIS_RELOAD
# SEC_CHECK_DISABLED



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello from Octo Organization
      
